INSERT INTO ROLE (ID, NAME)
SELECT 1, 'MANAGER'
WHERE NOT EXISTS (SELECT 1 FROM ROLE WHERE ID = 1);

INSERT INTO ROLE (ID, NAME)
SELECT 2, 'WORKER'
WHERE NOT EXISTS (SELECT 2 FROM ROLE WHERE ID = 2);
